[package]
name = "complexity-gate"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "complexity-gate"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
complexity-gate-core = { path = "../core", version = "=0.2.0" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
